// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sallon_Appointment_API.Data;

namespace Sallon_Appointment_API.Migrations
{
    [DbContext(typeof(Sallon_Appointment_APIContext))]
    [Migration("20210428104223_initailmigration2")]
    partial class initailmigration2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Sallon_Appointment_API.Models.Sallon", b =>
                {
                    b.Property<int>("Sallon_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Client")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Haircut")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hairdresser")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Sallon_ID");

                    b.ToTable("Sallon");
                });
#pragma warning restore 612, 618
        }
    }
}
